failed to find an instance named `b` specified as argument `` for instantiation `a`

Caused by:
    an import with name `b` does not exist