import `foo` conflicts with prior import of same name